check for Version produces an error
if "11.1.2.4" in (getFileVerInfo(__maxldll)):
TypeError: a bytes-like object is required, not 'str'

changed version string to bytes